GET http://localhost:3300/products



###


GET http://localhost:3300/products/621dc7f971c20aee2b47cb66


###


POST http://localhost:3300/products 
Content-Type: application/json

{
    "title": "Acer Nitro 5 i7 16GB RAM 256GB SSD+1TB HDD GTX1650 15 144Hz Laptop",
    "price": 19999,
    "category": "Laptop",
    "img": "https://i.postimg.cc/1ttVqpKf/acer-nitro-5an515-55-front-red-backlit-f8c0.jpg",
    "description": "fnksfsfs"
}



###


DELETE http://localhost:3100/products/621de90717708f54aa97a6a5
###



PATCH http://localhost:3100/products
Content-Type: application/json

{
    
}


###



GET http://localhost:3300/users

###
POST http://localhost:3300/users/signin
Content-Type:application/json

{
"fullname": "Kyle Mc Briden",
    "password": "123456hani2209"
}

###
POST http://localhost:3300/users/signup
Content-Type: application/json

{   
    "fullname": "Kyle Mc Briden",
    "password": "123456hani2209",
    "email": "happydayzz@gmail.com",
    "phone_number":"02133589303"
    
}

###

GET http://localhost:3300/cart
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMWYzYTY2YmUwMWZjYzNjNTU1ZDQ0MSIsImlhdCI6MTY0NjIxNDIxNCwiZXhwIjoxNjQ2MzAwNjE0fQ.Xzx5N_ZcbwKZ9rwPGbMp6xbEljn_nnDLDjdkXyJhERk


###

DELETE http://localhost:3300/cart/621cbb9c535b2cbb2f3f5fba
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjFjYmI5YzUzNWIyY2JiMmYzZjVmYmEiLCJjYXJ0IjpbXSwiaWF0IjoxNjQ2MDUwNjg3LCJleHAiOjE2NDYxMzcwODd9.NI5Mw7svm8BW7fZAtAi9z3lk08sMmmLuSZq9jyR_7wE

###

POST http://localhost:3300/cart/621dc7f971c20aee2b47cb66
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMWYzYTY2YmUwMWZjYzNjNTU1ZDQ0MSIsImlhdCI6MTY0NjIxMzc2MCwiZXhwIjoxNjQ2MzAwMTYwfQ.1INNIpyb0l6RSHZTZGx3dP0feZQiTOYQDkLHpXJ-nnE